### ISSUE TITLE
BibCirculation: retired CERN members

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1419]
Originally on 2013-03-21

If `CFG_CERN_SITE=1` (i.e. in CDS), BibCirculation assume the existence of the ccid identifier for borrowers. Additionaly it assumes borrowers are all included in LDAP.

This is actually not true for *retired people*.

In particular, in order to register as borrower a retired person one have to visit by hand the URL:
`/admin/bibcirculation/bibcirculationadmin.py/add_new_borrower_step1`.

There one can enter several details but not ccid.

In order to further introduce the ccid one have to go to the Python prompt and type:

```python
from invenio.dbquery import run_sql
email_of_borrower = "..."
ccid_of_borrower = "..."
run_sql("UPDATE crcBORROWER SET ccid=%s WHERE email=%s", (ccid_of_borrower, email_of_borrower))
```

This kind of sub-optimal. It should be possible for the Librarian to be able through the menus to reach `/admin/bibcirculation/bibcirculationadmin.py/add_new_borrower_step1` and to be able to fill in the `ccid`.

Of course this is a risky operation so enough verbiage should be given in order for the Librarian to be aware of the risk of inserting wrong ccid information for existing users.

**Comment by aw-bib** [comment]
Usually, you get/should get a library card in this case which contains some unique ID (usually a barcode). Probably, this abstraction from ccid -> user id helps out here?

**Comment by jirikuncar** [comment]
Can't we just create a local account for such user?

**Comment by aw-bib** [comment]
In most libraries this is connectes with issuing the library card. Please note thtat those "memberships" are usually time limited and need active prolongation by the user. Usually also connected with the request to return books.

**Comment by kaplun** [comment]
@jirikuncar this is a very specific CERN hack issue. Hopefully in the new implementation this can be indeed solved we native local users (in legacy bibcirculation we have a dedicated user table(!)). As @aw-bib some semplification to register a library card could be added (although this is surely overlay specific, so worth for demosite).

**Comment by tiborsimko** [comment]
@ludmilamarian @kasioumis @egabancho @switowski Is this fixed in CDS OPS?

**Comment by kaplun** [comment]
@tiborsimko I can tell you nope. The recipe in this issue is still used nowadays in real life.

**Comment by ludmilamarian** [comment]
@kaplun I haven't seen such a request in a long time. Is somebody from the Library taken care of running such a recipe?

**Comment by kaplun** [comment]
Yes: me :smile:

**Comment by ludmilamarian** [comment]
aaa, great! :) So, shall the implementation be left for master, or shall be addressed in legacy?

**Comment by kaplun** [comment]
Ah I guess we can leave it for master. It will be different anyway there.
