### ISSUE TITLE
login error caused by database error (relation "accounts_user" does not exist)

### ISSUE THREAD

**Issue by heidricha** [inveniosoftware/invenio#3767]
succesfully built, and up

all login attempt returns with 500: internal server error

logs:

web_1            | 172.17.0.8 - - [08/Mar/2017 15:16:47] "POST /login/ HTTP/1.0" 200 -
nginx_1          | 10.3.1.216 - - [08/Mar/2017:15:16:47 +0000] "POST /login/ HTTP/1.1" 200 3690 "http://10.3.1.78:8081/login/" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36" "-"
nginx_1          | 10.3.1.216 - - [08/Mar/2017:15:16:47 +0000] "GET /static/gen/styles.8f40cf0e.css HTTP/1.1" 304 0 "http://10.3.1.78:8081/login/" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36" "-"
nginx_1          | 10.3.1.216 - - [08/Mar/2017:15:16:47 +0000] "GET /static/images/invenio-color.svg HTTP/1.1" 304 0 "http://10.3.1.78:8081/login/" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36" "-"
nginx_1          | 10.3.1.216 - - [08/Mar/2017:15:16:47 +0000] "GET /static/gen/packed.98550d85.js HTTP/1.1" 304 0 "http://10.3.1.78:8081/login/" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36" "-"
postgresql_1     | ERROR:  relation "accounts_user" does not exist at character 557
postgresql_1     | STATEMENT:  SELECT accounts_user.id AS accounts_user_id, accounts_user.email AS accounts_user_email, accounts_user.password AS accounts_user_password, accounts_user.active AS accounts_user_active, accounts_user.confirmed_at AS accounts_user_confirmed_at, accounts_user.last_login_at AS accounts_user_last_login_at, accounts_user.current_login_at AS accounts_user_current_login_at, accounts_user.last_login_ip AS accounts_user_last_login_ip, accounts_user.current_login_ip AS accounts_user_current_login_ip, accounts_user.login_count AS accounts_user_login_count 
postgresql_1     | 	FROM accounts_user 
postgresql_1     | 	WHERE accounts_user.email ILIKE 'se@eli-alps.hu' 
postgresql_1     | 	 LIMIT 1
web_1            | [2017-03-08 15:16:58,566] ERROR in app: Exception on /login/ [POST]
web_1            | Traceback (most recent call last):
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
web_1            |     response = self.full_dispatch_request()
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
web_1            |     rv = self.handle_user_exception(e)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
web_1            |     reraise(exc_type, exc_value, tb)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
web_1            |     rv = self.dispatch_request()
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
web_1            |     return self.view_functions[rule.endpoint](**req.view_args)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_security/decorators.py", line 230, in wrapper
web_1            |     return f(*args, **kwargs)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_security/views.py", line 76, in login
web_1            |     if form.validate_on_submit():
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
web_1            |     return self.is_submitted() and self.validate()
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_security/forms.py", line 239, in validate
web_1            |     self.user = _datastore.get_user(self.email.data)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_security/datastore.py", line 191, in get_user
web_1            |     rv = self.user_model.query.filter(query).first()
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2731, in first
web_1            |     ret = list(self[0:1])
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2523, in __getitem__
web_1            |     return list(res)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2831, in __iter__
web_1            |     return self._execute_and_instances(context)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2854, in _execute_and_instances
web_1            |     result = conn.execute(querycontext.statement, self._params)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
web_1            |     return meth(self, multiparams, params)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
web_1            |     return connection._execute_clauseelement(self, multiparams, params)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
web_1            |     compiled_sql, distilled_params
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
web_1            |     context)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
web_1            |     exc_info
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
web_1            |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
web_1            |     context)
web_1            |   File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
web_1            |     cursor.execute(statement, parameters)
web_1            | ProgrammingError: (psycopg2.ProgrammingError) relation "accounts_user" does not exist
web_1            | LINE 2: FROM accounts_user 
web_1            |              ^
web_1            |  [SQL: 'SELECT accounts_user.id AS accounts_user_id, accounts_user.email AS accounts_user_email, accounts_user.password AS accounts_user_password, accounts_user.active AS accounts_user_active, accounts_user.confirmed_at AS accounts_user_confirmed_at, accounts_user.last_login_at AS accounts_user_last_login_at, accounts_user.current_login_at AS accounts_user_current_login_at, accounts_user.last_login_ip AS accounts_user_last_login_ip, accounts_user.current_login_ip AS accounts_user_current_login_ip, accounts_user.login_count AS accounts_user_login_count \nFROM accounts_user \nWHERE accounts_user.email ILIKE %(email_1)s \n LIMIT %(param_1)s'] [parameters: {'email_1': u'se@eli-alps.hu', 'param_1': 1}]
web_1            | 172.17.0.8 - - [08/Mar/2017 15:16:58] "POST /login/ HTTP/1.0" 500 -
nginx_1          | 10.3.1.216 - - [08/Mar/2017:15:16:58 +0000] "POST /login/ HTTP/1.1" 500 3704 "http://10.3.1.78:8081/login/" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36" "-"

**Comment by tiborsimko** [comment]
The login works fine on my local Invenio 3 demo instance. The problem you observed was most probably caused a transient issue with broken invenio-accounts v1.0.0b2 release on PyPI. The package was fixed yesterday in a new release v1.0.0b3, so it should be sufficient to upgrade your installation.  If this does not help, please reopen this issue.

**Comment by heidricha** [comment]
Thanks dealing with my problem!

Rebuilt after a pull. Build and start are OK without local "hacking" the config files, but the initial login still doesn't work. Maybe I don't know something (I don't for sure), but still I got the same error whatever I try to do on the opening page:
try to login
try to create user


The database looks like empty, Is there anywhere a create script I have to run by hand?

root@ef8eef32d2f9:/# psql -U invenio3 invenio3
psql (9.6.2)
Type "help" for help.

invenio3=# \dT
     List of data types
 Schema | Name | Description 
--------+------+-------------
(0 rows)
